# Generated by Django 6.1.1 on 2026-09-17 09:02

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('keywords', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dedupe_key'], name='jobs_joblis_dedupe__a071a8_idx'), models.Index(fields=['source'], name='jobs_joblis_source_8b426c_idx')],
            },
        ),
    ]
