# Generated by Django 6.1.1 on 2026-09-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
