# Generated by Django 6.1.1 on 2026-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='source_url',
            field=models.URLField(db_index=True),
        ),
    ]
